version: '3.8'

services:
  app:
    image: wallet_service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - env.app

  db:
    image: postgres:14.7-alpine
    container_name: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db_data:/var/lib/postgresql/data
    env_file:
      - env.db

volumes:
  db_data: